[package]
name = "unf-locality"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
aya.workspace = true
aya-obj = "0.3.0"
rustix.workspace = true
tempfile = "3.27.0"
thiserror.workspace = true
tokio.workspace = true
unf-cni-state = { path = "../unf-cni-state" }
unf-common = { path = "../unf-common" }
unf-ebpf-common = { path = "../../ebpf/unf-ebpf-common" }
unf-encryption = { path = "../unf-encryption" }
unf-link = { path = "../unf-link" }
unf-route = { path = "../unf-route" }

[dev-dependencies]
unf-ipam = { path = "../unf-ipam" }

[lints]
workspace = true
