[package]
name = "unf-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
aya.workspace = true
axum.workspace = true
clap.workspace = true
prometheus-client.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
unf-common = { path = "../../crates/unf-common" }
unf-cni-state = { path = "../../crates/unf-cni-state" }
unf-ebpf-common = { path = "../../ebpf/unf-ebpf-common" }
unf-ipam = { path = "../../crates/unf-ipam" }
unf-route = { path = "../../crates/unf-route" }
unf-state = { path = "../../crates/unf-state" }

[dev-dependencies]
tempfile = "3.27.0"

[lints]
workspace = true
