apiVersion: apps/v1
kind: Deployment
metadata:
  name: unf-controller
  namespace: unf-system
spec:
  template:
    spec:
      containers:
        - name: controller
          env:
            - name: UNF_CONTROLLER_LOAD_BALANCER_POOL_UID
              value: openshift-loadbalancer-pool-v1
            - name: UNF_CONTROLLER_LOAD_BALANCER_POOL_NAME
              value: qualification
            - name: UNF_CONTROLLER_LOAD_BALANCER_IPV4_POOL
              value: 198.51.100.240/28
            - name: UNF_CONTROLLER_LOAD_BALANCER_IPV6_POOL
              value: 2001:db8:ffff::f0/124
            - name: UNF_CONTROLLER_LOAD_BALANCER_PROVIDER_INSTANCE
              value: openshift-direct-node-v1
