[package]
name = "unf-cni"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
rustix = { workspace = true, features = ["process"] }
tokio.workspace = true
unf-cni-state = { path = "../../crates/unf-cni-state" }
unf-link = { path = "../../crates/unf-link" }
unf-route = { path = "../../crates/unf-route" }

[dev-dependencies]
tempfile = "3.27.0"
unf-ipam = { path = "../../crates/unf-ipam" }

[lints]
workspace = true
