apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../loadbalancer
images:
  - name: quay.io/arencloud/unf-controller-dev
    newName: quay.io/arencloud/unf-controller-dev
    digest: sha256:c0df4e393249c39505a465cc46b1feb975abfaf6cbf69ead67a92498cbe62760
  - name: quay.io/arencloud/unf-agent-dev
    newName: quay.io/arencloud/unf-agent-dev
    digest: sha256:a3904c2a1b31da3abfbe81426099786dbdb4a8c9b454ddd0a86e9b2181801533
