apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../loadbalancer
images:
  - name: quay.io/arencloud/unf-controller-dev
    newName: quay.io/arencloud/unf-controller-dev
    digest: sha256:43c92bf14e49079225c5602c26edcf3cd2d5759bc65d6b305140a82c24f660b2
  - name: quay.io/arencloud/unf-agent-dev
    newName: quay.io/arencloud/unf-agent-dev
    digest: sha256:df5f7818e83ddd93365181b8fcddb2ebcd4bee9ed7392dca08d781ee4a9333a7
