apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/network.unf.io_securitypolicies.yaml
  - crds/network.unf.io_egresspools.yaml
  - crds/network.unf.io_egresspolicies.yaml
  - kubernetes
