[package]
name = "unf-encryption"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures.workspace = true
genetlink.workspace = true
getrandom.workspace = true
netlink-packet-core.workspace = true
netlink-packet-generic.workspace = true
netlink-packet-wireguard.workspace = true
rtnetlink.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
unf-common = { path = "../unf-common" }
x25519-dalek.workspace = true
zeroize.workspace = true

[dev-dependencies]
proptest.workspace = true
tempfile = "3.27.0"

[lints]
workspace = true
