[package]
name = "unf-controller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
axum-server.workspace = true
clap.workspace = true
futures.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
prometheus-client.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
unf-api = { path = "../../crates/unf-api" }
unf-common = { path = "../../crates/unf-common" }
unf-ipam = { path = "../../crates/unf-ipam" }
unf-policy = { path = "../../crates/unf-policy" }
unf-state = { path = "../../crates/unf-state" }

[lints]
workspace = true
