apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../egress
images:
  - name: quay.io/arencloud/unf-controller-dev
    newName: quay.io/arencloud/unf-controller-dev
    digest: sha256:acab9a2185b1457307e48b113ec41f40cb95b9d61729befe0a7ad58f1c0cc59c
  - name: quay.io/arencloud/unf-agent-dev
    newName: quay.io/arencloud/unf-agent-dev
    digest: sha256:0b34041ea3e151605f23579d8d8904cd607436ec8057ffe03a3dc8bea7753987
patches:
  - path: controller-native-patch.yaml
  - path: agent-rotation-patch.yaml
