apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../egress
images:
  - name: quay.io/arencloud/unf-controller-dev
    newName: quay.io/arencloud/unf-controller-dev
    digest: sha256:e23fc788e41c459fbfcd45350642f65bd58bc7a9b18fe4976d45c89e36235d8c
  - name: quay.io/arencloud/unf-agent-dev
    newName: quay.io/arencloud/unf-agent-dev
    digest: sha256:222e252fa0513b3f77ca44e376775a869d427ef88cff0dbe66c8ec60212ea91b
patches:
  - path: controller-native-patch.yaml
  - path: agent-rotation-patch.yaml
