apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../egress
images:
  - name: quay.io/arencloud/unf-controller-dev
    newName: quay.io/arencloud/unf-controller-dev
    digest: sha256:d0fd2b3dbf30f64efdbc711cd3e0b1908e18ff92fe79083fb997560e30212f5f
  - name: quay.io/arencloud/unf-agent-dev
    newName: quay.io/arencloud/unf-agent-dev
    digest: sha256:629fbbf087e46958d5f4ae5c8b53af50c2e23cd40bccf4f61a6ab22a502b8e73
patches:
  - path: controller-native-patch.yaml
  - path: agent-rotation-patch.yaml
