[package]
name = "unf-route"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
unf-cni-state = { path = "../unf-cni-state" }
unf-link = { path = "../unf-link" }

[dev-dependencies]
unf-ipam = { path = "../unf-ipam" }

[lints]
workspace = true
