apiVersion: apps/v1
kind: Deployment
metadata:
  name: unf-controller
  namespace: unf-system
spec:
  template:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - operator: Exists
