apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../crds
  - ../../kubernetes
  - primary-scc.yaml
  - primary-host-mount-policy.yaml
configMapGenerator:
  - name: unf-cni-install
    namespace: unf-system
    files:
      - 10-unf.conflist
      - install.sh
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: localhost/unf-controller:dev
    newName: quay.io/arencloud/unf-controller-dev
    digest: sha256:b4df5645ac3a2ea9552f7a21d2d0d81c7d7c4aa1ea8355e2c6f304c2f2be3d56
  - name: localhost/unf-agent:dev
    newName: quay.io/arencloud/unf-agent-dev
    digest: sha256:e94e58150d3bb8756ab3c298db7d36dd0b9a1bd7bec1ffc6bb03f6e986a60fb9
patches:
  - path: controller-patch.yaml
  - path: agent-patch.yaml
