apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../crds
  - ../../kubernetes
  - primary-scc.yaml
  - primary-host-mount-policy.yaml
configMapGenerator:
  - name: unf-cni-install
    namespace: unf-system
    files:
      - 10-unf.conflist
      - install.sh
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: localhost/unf-controller:dev
    newName: quay.io/arencloud/unf-controller-dev
    digest: sha256:532ed06a91ab636b27ac8dca7457b24d10cf5765bc4b7904333da5eebed08d85
  - name: localhost/unf-agent:dev
    newName: quay.io/arencloud/unf-agent-dev
    digest: sha256:17efacea6d20d2bf26cef5f0b5adfbf03c99c05f694d793de931a0f036329c86
patches:
  - path: controller-patch.yaml
  - path: agent-patch.yaml
