apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../crds
  - ../../kubernetes
  - primary-scc.yaml
  - primary-host-mount-policy.yaml
configMapGenerator:
  - name: unf-cni-install
    namespace: unf-system
    files:
      - 10-unf.conflist
      - install.sh
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: localhost/unf-controller:dev
    newName: quay.io/arencloud/unf-controller-dev
    digest: sha256:d0ed5d47fd0fd3f09e609465490632913b20bfae0be5190029e64bdc0ae6f644
  - name: localhost/unf-agent:dev
    newName: quay.io/arencloud/unf-agent-dev
    digest: sha256:32b9fac0ceeda1c8a0adc7d60d6827c7f9244dcf38c72338b35d9ab9e2bd716e
patches:
  - path: controller-patch.yaml
  - path: agent-patch.yaml
