apiVersion: v1
kind: ServiceAccount
metadata:
  name: unf-controller
  namespace: unf-system
imagePullSecrets:
  - name: unf-quay-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unf-agent
  namespace: unf-system
imagePullSecrets:
  - name: unf-quay-pull
