apiVersion: v1
kind: ConfigMap
metadata:
  name: unf-agent-acknowledgements
  namespace: unf-system
  labels:
    app.kubernetes.io/name: unf-controller
    app.kubernetes.io/component: durable-agent-state
