apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - rbac.yaml
  - agent-report-store.yaml
  - flow-history-store.yaml
  - topology-history-store.yaml
  - load-balancer-store.yaml
  - controller.yaml
  - service.yaml
  - agent.yaml
