apiVersion: v1
kind: ConfigMap
metadata:
  name: unf-load-balancer-status-ownership
  namespace: unf-system
  labels:
    app.kubernetes.io/name: unf-controller
    app.kubernetes.io/component: durable-load-balancer-status-ownership
data: {}
