apiVersion: v1
kind: Service
metadata:
  name: unf-controller
  namespace: unf-system
spec:
  selector:
    app.kubernetes.io/name: unf-controller
  ports:
    - name: http
      port: 9962
      targetPort: http
    - name: https-internal
      port: 9964
      targetPort: https-internal
